### ISSUE TITLE
Not an issue, but rather a question...

### ISSUE THREAD

**Issue by davidstanley01** [james2doyle/pyro-pagewidgets-field#1]
First, great work.  I've been looking for something like this, so, again, huge thanks.  My question is simply, "how do I install this?" I've placed it in the addons/shared_addons/widgets directory, but I can't find it in the admin interface.  Thanks.

**Comment by james2doyle** [comment]
I think I know what's up. You need to have your directory setup like this `addons/shared_addons/widgets/pagewidgets`

I assume you extracted this whole repo into the widgets folder. Which won't work. the `pagewidgets` folder needs to be the top level under widgets.

**Comment by davidstanley01** [comment]
That's how I have it set up, actually.  I'm not sure if there is something else I need to do or not.  Thanks!
![Screen Shot 2013-04-15 at 8 24 13 PM](https://f.cloud.github.com/assets/844070/384012/6f1fcad8-a634-11e2-85ac-07848e68d602.png)

**Comment by james2doyle** [comment]
OH! Oops so sorry. This is a Field Type. Not a widget. It should be in the Field Types directory. It just pulls widgets so you can apply them to a page.

**Comment by davidstanley01** [comment]
That helped.  Thanks. I'll keep working on it and run it down.

**Comment by davidstanley01** [comment]
Ok.  One last thing and then I'll quit bugging you...  I've defined a widget area called general ( {{ widgets:area slug="general" }} ) and placed three widgets in there.  For the page in question, I've created a field called, "callouts" and assigned each of the three widgets previously mentioned to that page.  Per the README file, I am attempting to call the objects within the page template according to the screenshot attached. What am I doing wrong (if you can tell by the info given)?  I'm sorry to keep bugging you on this...
![Screen Shot 2013-04-15 at 9 17 45 PM](https://f.cloud.github.com/assets/844070/384117/477d955c-a63c-11e2-9698-fe4d5535cf2a.png)

**Comment by davidstanley01** [comment]
I should also mention, I've also created a separate widget area called (you guessed it) sidebar.  While I haven't added any widgets to that, I certainly can.  Thx.

**Comment by james2doyle** [comment]
Hmmmm. I will have to look into it. It might not be your fault. I will have to get back to you tomorrow.

**Comment by james2doyle** [comment]
Ok. I think I got it. Recently something changed with the way the pages are rendered. 

You need to use `page:callouts` to access the page variables. 

Try that and let me know.

**Comment by davidstanley01** [comment]
Ok. I'll take a look tonight and get back to you.  Thanks, again, for the help.

**Comment by davidstanley01** [comment]
Worked great.  Thanks.
