### ISSUE TITLE
Undefined offset:0 - if no widget for the page are exists

### ISSUE THREAD

**Issue by noxify** [james2doyle/pyro-pagewidgets-field#2]
Hi,

i have the problem, that i got everytime a server notice,
if no page widgets are defined for the current page in the admin panel.

```
A PHP Error was encountered

Severity: Notice
Message: Undefined offset: 0
Filename: pagewidgets/field.pagewidgets.php
Line Number: 99
```

Line 99 is:

```
return '<div id="widget_page">'.form_multiselect($data['form_slug'].'[0][]', $widget_list, $output[0]).$template.'</div>';
```

Tested with:
- Pyrocms 2.2.1 Community Edition (Unix Server)
- Pyrocms 2.2.1 Professional (local - OSX - MAMP)

Thanks a lot.

**Comment by james2doyle** [comment]
I'm having trouble re-creating this issue. Can you explain exactly what you did to make this occur?

**Comment by noxify** [comment]
Hi,

sorry for the delay.

I updated my online version to the current pyro pro version.

url: http://demo.webstone.info/admin/
user: demo@demo.com
pass: demouser

I have the problem with new pages.

You can edit the "Home" page without problems.
But if you edit the "Test" page (or you create your own) you will see an error
message at the top of the content page.

If you add a widget to the page - no error will be shown.

Hope this helps.

Thanks!

**Comment by james2doyle** [comment]
I am only able to re-create this issue on your setup.

I set up a new version of pyro and installed this field type. I was never able to get this error to show up. How is it running locally? Would you mind just installing a fresh version and testing it?

**Comment by noxify** [comment]
Hi,

i've installed a fresh pyro pro 2.2.1 on my local environment.
But I have the same problem.

I downloaded the source from the github repo.

Local Environment:
- OSX 10.8 (with MAMP)
- PHP: 5.2.17
- mySQL: 5.5.25 
- Pyro Pro: 2.2.1
- Page Widgets: 1.0.1

And i tested the community edition (2.2.1) and I have the problem, too.

Any ideas?
Maybe we can create a "temporary" workaround ;)

###UPDATE

If I replace the $output[0] 

```
return '<div id="widget_page">'.form_multiselect($data['form_slug'].'[0][]', $widget_list, $output[0]).$template.'</div>';
```

with $output[1]

```
return '<div id="widget_page">'.form_multiselect($data['form_slug'].'[0][]', $widget_list, $output[1]).$template.'</div>';
```

it is working fine.

But is this correct?

`var_dump($output[0]);`

Returns "NULL" without defined page widgets. 

###UPDATE 2

I use now this code - this a good workaround for me :)

```
if (strlen($output[1]) == 0)
{
    return '<div id="widget_page">'.form_multiselect($data['form_slug'].'[0][]', $widget_list, $output[1]).$template.'</div>';
}
else
{
    return '<div id="widget_page">'.form_multiselect($data['form_slug'].'[0][]', $widget_list, $output[0]).$template.'</div>';
}
```

**Comment by james2doyle** [comment]
We will keep this open in case anyone else has this issue. It isn't a hard fix but hopefully if other people are getting this error they point it out.
